before_script:
  - |
    if ! command -v scala-cli &> /dev/null
    then
      echo "Installing scala-cli..."
      curl -fLo cs https://git.io/coursier-cli-"$(uname | tr LD ld)"
      chmod +x cs
      ./cs install scala-cli
    else
      echo "scala-cli is already installed."
    fi

stages:
  - build
  - test

build-job:
  stage: build
  script: 
    - ls
    - make

test_job:
  stage: test
  script:
    - scala-cli test . > test_output.txt || true
    - FAILED_TESTS=$(grep -c "FAILED" test_output.txt)
    - echo "Number of tests failed: $FAILED_TESTS"
  artifacts:
    paths:
      - test_output.txt
  allow_failure: true
