stages:
  - build
  - test

build-job:
  stage: build
  image: gumjoe/wacc-ci-scala:slim
  script: 
    - ls
    - scala-cli --power package . --server=false --jvm system --force

test_job:
  stage: test
  image: gumjoe/wacc-ci-scala:slim
  script:
    - scala-cli --power test .
  artifacts:
    paths:
      - test_output.txt
  
