stages:
  - build
  - test

build-job:
  stage: build
  image: jamacz/scala-cli:latest
  script: 
    - ls
    - make

test_job:
  stage: test
  image: jamacz/scala-cli:latest
  script:
    - scala-cli test .
  artifacts:
    paths:
      - test_output.txt
  allow_failure: true
